### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by itzmanish** [GraphCMS/graphcms-image#15]
This is not working.
code snippet:
```
<GraphImg
withWebp
key={service.image.handle}
alt={service.title}
image={service.image.handle}
className="w-full"
/>
```

GatsbyJS

**Comment by notrab** [comment]
Hey @itzmanish 

I imagine you got this resolved, but the issue is. most likely you're passing the `handle` to `image` prop, where it should be the `image` object including `width`, `height`, and `handle`.
