### ISSUE TITLE
SVG support?

### ISSUE THREAD

**Issue by jhnns** [GraphCMS/graphcms-image#16]
Hi there 👋

what's the current state of SVG support? It looks like graphcms-image doesn't support SVGs coming from the CMS since the `width` and `height` will be `0`. And even if I set the `width` and `height` to something, it will request the image with options that are not supported for SVGs, such as: `https://media.graphcms.com/resize=w:20,h:20,fit:crop/blur=amount:2/compress/12345567`

If you don't plan to support SVGs I think it would be a good idea to mention that in the README 😄

**Comment by notrab** [comment]
Hey,

Right now you're right, the CMS doesn't return the width/height of SVGs which is required for this to operate. You could provide these manually to the component, but that sounds painful.

I'll explore a few ideas what we can do to help, but for now I'll add a note to the README.

**Comment by smithki** [comment]
Any suggestions or workarounds here? Seems to me this is still an issue; can this be re-opened?
