### ISSUE TITLE
height collapses before blurry placeholder loads

### ISSUE THREAD

**Issue by brandonmp** [GraphCMS/graphcms-image#2]
gif of symptoms below. Not sure if this has to do with SSR or not.

I'm using nextjs w/ Apollo, calling image with dimensions of 576x576 like so:

```
const Image = (props: Props) =>
    typeof window !== 'undefined'
        && 
     // as far as i can tell this container is required b/c the image is
     // positioned absolutely
     <div
              style={{
                  position: 'relative',
                  minHeight: 500,
                  maxWidth: 600
              }}
          >
              <GraphImage
                  image={props.image}
                  alt={props.alt}
                  maxWidth={600}
              />
          </div>
```

![graphcms-img](https://user-images.githubusercontent.com/14139991/35351430-dda5f024-010e-11e8-8fd9-b159727c354a.gif)

**Comment by hmeissner** [comment]
Could you try this without using the styled `div` container? It is not required because while `img` is absolutely positioned, it is kept inside a relative positioned `div` along with an empty one that holds the image position with padding matching the aspect ratio.

**Comment by brandonmp** [comment]
@hmeissner  I'll try to set that up a little later, but in the mean time I wanted to note that I added the `div` because the image was taking up `100vw`, so I assumed the top-level export of `graphcms-image` was positioned absolutely. 

Not sure why it was blowing up if the top-level export is `relative`, though, so i'll let you know if i can take a look

**Comment by brandonmp** [comment]
also, not sure if relevant, but note that the alt text for the image doesn't render initially, and isn't visible until just before the image renders--could be b/c of the `typeof window !== 'undefined'` guards in the component?

**Comment by hmeissner** [comment]
`typeof window !== 'undefined'` guard is actually unnecessary, the component should work 100% fine with Next.js without it.

**Comment by hmeissner** [comment]
Closing, if you have any more issues using `graphcms-image` in your app, feel free to let me know at https://slack.graphcms.com/ :)
