### ISSUE TITLE
Bug in srcset

### ISSUE THREAD

**Issue by wildpow** [GraphCMS/graphcms-image#4]
It seems the srcset is defaulting to crop instead of what the I passed in.

How I used Graphcms-image:
` <GraphImg image={Carousel.sale} maxWidth={500} withWebp={true} fit="clip"/>`

and whats produced in the DOM is:
`<img alt title srcset = "https://media.graphcms.com/resize=w:125,fit:crop/output=format:webp /compress/uX62fSseS7KunpogTBJe 125w, https://media.graphcms.com/resize=w:250,fit:crop/output=format:webp
/compress/uX62fSseS7KunpogTBJe 250w, https://media.graphcms.com/resize=w:500,fit:crop/output=format:webp
/compress/uX62fSseS7KunpogTBJe 500w, https://media.graphcms.com/resize=w:600,fit:crop/output=format:webp
/compress/uX62fSseS7KunpogTBJe 600w" src="https://media.graphcms.com/resize=w:600,h:600,fit:clip/output=format:webp
/compress/uX62fSseS7KunpogTBJe" sizes="(max-width: 500px) 100vw, 500px" style="position: absolute; top: 0px; left: 0px; transition-duration: 0.5s; transition-timing-function: initial; transition-property: opacity; opacity: 1; width: 100%; height: 100%; object-fit: cover; object-position: center center;">`

I'm using GraphCMS image version 1.1.0-beta3

**Comment by hmeissner** [comment]
Fixed wth https://github.com/GraphCMS/graphcms-image/commit/0d45065824cd585c614a9818f2b1a18080dbb3fa

**Comment by wildpow** [comment]
You are a gentleman and a scholar.
