### ISSUE TITLE
style prop is applied to graphcms-image-wrapper, not to inner img element

### ISSUE THREAD

**Issue by RenovationMan** [GraphCMS/graphcms-image#6]
It seems styles are applied to the outer div element with class graphcms-image-wrapper instead of the inner image element. While it can be convenient to abstract the fact that the image is wrapped inside a container by the component, it does not allow users to set styles properties on the image, such as object-position or object-fit for instance.

**Comment by RenovationMan** [comment]
Thanks @hmeissner.

IMHO the second solution would be more versatile as it would allow users to target specific images for styling. Relying on CSS scoping can be quite annoying. 

Alternatively, I believe gatsby-image exposes two style properties, one for the wrapper and one for the image. This could be useful to use CSS in JS stylings, e.g. styled-components.

Are PRs welcome ?

**Comment by hmeissner** [comment]
Sorry for such a late response 😞  PRs are more than welcome! 🙌
