### ISSUE TITLE
lazy-loading and fade still happen on subsequent mounts with Gatsby

### ISSUE THREAD

**Issue by wildpow** [GraphCMS/graphcms-image#7]
Observing lazing-loading and fading after subsequent mounts with Gatsby v2.
[Here is a test project](https://github.com/wildpow/Test-gatsby-with-graphCMS-image).
You will have to come up with your own API URL to make this project run.

The first image is a plain `img` tag with data from a `StaticQuery` component, second is GrapgCMS-image from the same data source. The 3rd gets data from Apollo Client. This issue doesn't seem to effect a CRA project.

**Comment by notrab** [comment]
Hey @wildpow 

We're hoping to make some changes to this repo soon that might address this.

Since this issue is rather quiet, I'll reopen if I hear from others experiencing this also.
