### ISSUE TITLE
`style.width` required?

### ISSUE THREAD

**Issue by SpainTrain** [GraphCMS/graphcms-image#9]
The way styles are setup, it seems like `style.width`, or applying a class with scalar width, is required to make this component display correctly.  Am I understanding this?  If I am correct, I am happy to PR a README update that clarifies how this component must be used. Thanks!

**Comment by IsraaMoqbel** [comment]
Thank you, you saved my day!
I tried to add `width` property but it didn't work, I thought of this solution but I just excluded it and didn't even bother myself trying it until I saw your issue!

**Comment by notrab** [comment]
You must pass in an image `handle`, `height`, and `width` for this to work.

```graphql
allAssets {
    handle
    width
    height
  }
```

We'll be updating the README, and repo to cover some more examples soon.
